# -*- coding: utf-8 -*-
"""Day-1_449.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PVOe-6dqmrGM3NSIh5WMyqR5rVbZEf0W
"""

# Declare variables of different data types
integer_var = 10
float_var = 20.5
string_var = "Hello, Vamshi!"
boolean_var = True


print("Integer Variable:", integer_var, "- Type:", type(integer_var))
print("Float Variable:", float_var, "- Type:", type(float_var))
print("String Variable:", string_var, "- Type:", type(string_var))
print("Boolean Variable:", boolean_var, "- Type:", type(boolean_var))