# -*- coding: utf-8 -*-
"""Day-4_449.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18A26w56IF3E0xIMSRt2qygRJWHzSqbFa
"""

# Function to calculate the sum of all even numbers up to n
def sum_of_even_numbers(n):
    total = 0
    for i in range(1, n + 1):
        if i % 2 == 0:
            total += i
    return total
n = int(input("Enter a positive integer: "))
if n > 0:
    result = sum_of_even_numbers(n)
    print(f"The sum of all even numbers between 1 and {n} is: {result}")
else:
    print("Please enter a positive integer.")