# -*- coding: utf-8 -*-
"""Day-2_449.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Yy-nz-cQ9oP1es9-dIw0Xi8BexmU322_
"""

my_list = [10, 20, 30, 40, 50]

my_tuple = ("apple", "banana", "cherry", "date", "elderberry")

my_dict = {"name": "Vamshi", "age": 25, "city": "Hyderabad", "hobby": "coding", "language": "Python"}

print("List Example:")
print("Element at index 0:", my_list[0])
print("Element at index 3:", my_list[3])

print("\nTuple Example:")
print("Element at index 1:", my_tuple[1])
print("Element at index 4:", my_tuple[4])

print("\nDictionary Example:")
print("Value for key 'name':", my_dict["name"])
print("Value for key 'hobby':", my_dict["hobby"])

print("\nAdditional Access Examples:")
print("Slice List (elements at index 1 to 3):", my_list[1:4])
print("Slice Tuple (first three elements):", my_tuple[:3])